### ISSUE TITLE
漢字変換すると落ちる

### ISSUE THREAD

**Issue by konnyakmannan** [saitoha/sentimental-skk#1]
MacOSX(10.8)のターミナル.appでsskkを利用しています．

vimを使って日本語の文章を書いていたところ 漢字変換をするとsskkが落ちます．
落ちたあと

``` zsh
sskk aborted by an uncaught exception. see $HOME/.sskk/log/log.txt.
```

というメッセージがでます．

あとzshのコマンドライン上で漢字変換をすると…

たとえば

``` zsh
$ ▽かんだ
```

と入力すると

``` zsh
$ 田
```

のように最初の一文字目の漢字が消えてしまいます．

今，わかっているエラーは以上です．
iterm2に関しては使っていないのでわかりません．

**Comment by saitoha** [comment]
落ちた直後の$HOME/.sskk/log/log.txtの内容がわかれば教えて下さい。

あと、文字ずれの方もこっちで再現しないのでいろいろ想像しているんですが、
GNU Screen / tmux / dvtm のようなターミナルマルチプレクサを使っているかと、
screenを使っている場合はcjkwidthオプションがonになっているか、と、
Terminal.appの設定で、「Unicode 東アジア A (曖昧) の文字幅をW (広) にする」にチェックが入ってるかと、
Terminal.appにmouseterm / mouseterm-plus などのSIMBL系プラグインを入れているかと、
zshのプロンプトで絵文字などの複雑なプロンプトを使用しているかと、
あとは可能ならscriptコマンドで問題となる現象が起きている時のログを作ってもらえればかなり役に立つと思います。
たくさん聞いちゃってすみません。

**Comment by konnyakmannan** [comment]
log.txtの中身はつぎのようになりました．

``` txt
ERROR:root:Aborted by exception.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sskk/sskk.py", line 239, in main
    outputhandler=multiplexer)
  File "/usr/local/lib/python2.7/site-packages/sskk/canossa/canossa/tff/tff/tff.py", line 730, in start
    self.drive()
  File "/usr/local/lib/python2.7/site-packages/sskk/canossa/canossa/tff/tff/tff.py", line 634, in drive
    self.process_input(data)
  File "/usr/local/lib/python2.7/site-packages/sskk/canossa/canossa/tff/tff/tff.py", line 523, in process_input
    self._inputparser.parse(data)
  File "/usr/local/lib/python2.7/site-packages/sskk/canossa/canossa/tff/tff/parser.py", line 98, in parse
    context.dispatch_char(c)
  File "/usr/local/lib/python2.7/site-packages/sskk/canossa/canossa/tff/tff/tff.py", line 292, in dispatch_char
    if not self.__handler.handle_char(self, c):
  File "/usr/local/lib/python2.7/site-packages/sskk/input.py", line 522, in handle_char
    if clauses and listbox.handle_char(context, c):
  File "/usr/local/lib/python2.7/site-packages/sskk/canossa/canossa/popup.py", line 659, in handle_char
    if self._listener.oninput(self, context, c):
  File "/usr/local/lib/python2.7/site-packages/sskk/input.py", line 94, in oninput
    self.onsettled(listbox, context)
  File "/usr/local/lib/python2.7/site-packages/sskk/input.py", line 159, in onsettled
    self._settle(context)
  File "/usr/local/lib/python2.7/site-packages/sskk/input.py", line 360, in _settle
    dictionary.feedback(key, value)
  File "/usr/local/lib/python2.7/site-packages/sskk/dictionary.py", line 82, in feedback
    user_dict_file = open(path, 'a+')
IOError: [Errno 13] Permission denied: '/Users/kanda_t/.sskk/userdict/1386114065.tmp'
```

あと文字ずれですが 今あらためて確認したところ 再現できませんでした．
zshのコマンドライン上でも前述したのと同じように漢字変換で落ちます．

今はscreenもtmuxも使っていません．

昨日なぜ文字ずれがおこったのかは謎です．

> たくさん聞いちゃってすみません。

いえいえ，こちらこそ対応していただきたすかります．

**Comment by saitoha** [comment]
一応再現しました。
~/.sskk/userdict が別のユーザの権限で作成された可能性があります。

```
% rm -rf ~/.sskk/userdict
% sudo sskk

... <変換・確定操作を行う> ...

% exit
% sskk

... <変換・確定操作を行う> ...
```

   --> エラー

対策は、

```
sudo chown -R $USER ~/.sskk
```

でいいと思います。

**Comment by konnyakmannan** [comment]
ありがとうございます．

chownすることで変換操作ができました．

ありがとうございました．
