### ISSUE TITLE
▽だけが出ている状態のときに <C-n> を押すと落ちる

### ISSUE THREAD

**Issue by todashuta** [saitoha/sentimental-skk#2]
手順を書きます
- sskk を起動
- `<C-j>` でひらがなモードに移行
- ``~!@#$%^&*()-_=+{}\|'"<>/?` のうち、どれかひとつのキーを入力して▽が表示された状態にする
- その状態で`<C-n>`を押す
- sskk aborted by an uncaught exception. see $HOME/.sskk/log/log.txt. と表示されて落ちる

試した環境は
- Ubuntu 12.04LTS + pyenv (python 2.7.6)
- OS X 10.8 + pyenv (python 2.7.5)

で、どちらでも起こりました。

~/.sskk/log/log.txt の内容を貼り付けておきます。

```
ERROR:root:Aborted by exception.
Traceback (most recent call last):
  File "/Users/todashuta/.pyenv/versions/2.7.5/lib/python2.7/site-packages/sskk/sskk.py", line 239, in main
    outputhandler=multiplexer)
  File "/Users/todashuta/.pyenv/versions/2.7.5/lib/python2.7/site-packages/sskk/canossa/canossa/tff/tff/tff.py", line 730, in start
    self.drive()
  File "/Users/todashuta/.pyenv/versions/2.7.5/lib/python2.7/site-packages/sskk/canossa/canossa/tff/tff/tff.py", line 634, in drive
    self.process_input(data)
  File "/Users/todashuta/.pyenv/versions/2.7.5/lib/python2.7/site-packages/sskk/canossa/canossa/tff/tff/tff.py", line 523, in process_input
    self._inputparser.parse(data)
  File "/Users/todashuta/.pyenv/versions/2.7.5/lib/python2.7/site-packages/sskk/canossa/canossa/tff/tff/parser.py", line 98, in parse
    context.dispatch_char(c)
  File "/Users/todashuta/.pyenv/versions/2.7.5/lib/python2.7/site-packages/sskk/canossa/canossa/tff/tff/tff.py", line 292, in dispatch_char
    if not self.__handler.handle_char(self, c):
  File "/Users/todashuta/.pyenv/versions/2.7.5/lib/python2.7/site-packages/sskk/input.py", line 578, in handle_char
    self._showpopup()
  File "/Users/todashuta/.pyenv/versions/2.7.5/lib/python2.7/site-packages/sskk/input.py", line 402, in _showpopup
    self._convert_word()
  File "/Users/todashuta/.pyenv/versions/2.7.5/lib/python2.7/site-packages/sskk/input.py", line 299, in _convert_word
    if len(result) > 5 or key[0] == '@':
IndexError: string index out of range
```

**Comment by saitoha** [comment]
直してPyPIに上げました。
0.0.102です。
thanks!

**Comment by todashuta** [comment]
upgrade して直っているのを確認しました。
対応ありがとうございます！
