### ISSUE TITLE
不要なor誤ったShiftを押すと落ちる

### ISSUE THREAD

**Issue by todashuta** [saitoha/sentimental-skk#3]
skk での入力としては変な入力ですが…(笑)

いろいろ試したところ、以下のように不要なor誤ったShiftを押すと
`sskk aborted by an uncaught exception. see $HOME/.sskk/log/log.txt.`
が出て落ちることがわかりました。

(大文字はShiftキーを押しながらです)
- NihongonyuuRyo
- Kyari-paMyu
- NekogaNya

以下に $HOME/.sskk/log/log.txt の内容を添付させていただきたく。

```
ERROR:root:Aborted by exception.
Traceback (most recent call last):
  File "/Users/todashuta/.pyenv/versions/2.7.5/lib/python2.7/site-packages/sskk/sskk.py", line 239, in main
    outputhandler=multiplexer)
  File "/Users/todashuta/.pyenv/versions/2.7.5/lib/python2.7/site-packages/sskk/canossa/canossa/tff/tff/tff.py", line 737, in start
    self.drive()
  File "/Users/todashuta/.pyenv/versions/2.7.5/lib/python2.7/site-packages/sskk/canossa/canossa/tff/tff/tff.py", line 641, in drive
    self.process_input(data)
  File "/Users/todashuta/.pyenv/versions/2.7.5/lib/python2.7/site-packages/sskk/canossa/canossa/tff/tff/tff.py", line 530, in process_input
    self._inputparser.parse(data)
  File "/Users/todashuta/.pyenv/versions/2.7.5/lib/python2.7/site-packages/sskk/canossa/canossa/tff/tff/parser.py", line 98, in parse
    context.dispatch_char(c)
  File "/Users/todashuta/.pyenv/versions/2.7.5/lib/python2.7/site-packages/sskk/canossa/canossa/tff/tff/tff.py", line 292, in dispatch_char
    if not self.__handler.handle_char(self, c):
  File "/Users/todashuta/.pyenv/versions/2.7.5/lib/python2.7/site-packages/sskk/input.py", line 524, in handle_char
    if clauses and listbox.handle_char(context, c):
  File "/Users/todashuta/.pyenv/versions/2.7.5/lib/python2.7/site-packages/sskk/canossa/canossa/popup.py", line 659, in handle_char
    if self._listener.oninput(self, context, c):
  File "/Users/todashuta/.pyenv/versions/2.7.5/lib/python2.7/site-packages/sskk/input.py", line 137, in oninput
    self.onsettled(listbox, context)
  File "/Users/todashuta/.pyenv/versions/2.7.5/lib/python2.7/site-packages/sskk/input.py", line 159, in onsettled
    self._settle(context)
  File "/Users/todashuta/.pyenv/versions/2.7.5/lib/python2.7/site-packages/sskk/input.py", line 362, in _settle
    dictionary.feedback(key, value)
  File "/Users/todashuta/.pyenv/versions/2.7.5/lib/python2.7/site-packages/sskk/dictionary.py", line 170, in feedback
    if key[0] == '@':
IndexError: string index out of range
```

**Comment by todashuta** [comment]
upgrade して直っているのを確認しました。ありがとうございます。
